### PR TITLE
Enable odata-client-php for Laravel 8

### PR DESCRIPTION
**Pull request by newtongamajr**
Hello @anderly 

In order to work with Laravel 8.

### CODE REVIEW

**Comment by clandestine8** [comment]
When Merged wthis will resolve https://github.com/saintsystems/odata-client-php/issues/63

**Comment by newtongamajr** [comment]
Hello @anderly 

In fact, Laravel 8 requires PHP 7.3 or higher. That's why CI checks failed during integration phase.

Best regards!

**Comment by quintenbuis** [comment]
When is this getting merged?

**Comment by quintenbuis** [comment]
I've opened a new PR to add compatibility with laravel 8. #66

**Comment by anderly** [comment]
@newtongamajr is this PR still needed if we merge #66?

**Comment by newtongamajr** [comment]
Hi @anderly. I don't think it'll be necessary anymore if #66 is applied! Thank's

**Comment by anderly** [comment]
Closed by #66

**Pull request closed without merging**
