### PR TITLE
Add compatibility with laravel 8

### PR DESCRIPTION
**Pull request by quintenbuis**
Add compatibility with laravel 8

### CODE REVIEW

**Comment by quintenbuis** [comment]
This PR will fix: #63

**Comment by quintenbuis** [comment]
It also removes support for PHP7.2.

**Comment by PieterCappelle** [comment]
Could this one please be merged? Thanks!

**Comment by quintenbuis** [comment]
@anderly @AaronKaa @nicam Can someone fix travis and merge this?

**Comment by anderly** [comment]
@quintenbuis, would you mind adding one change to this PR to simply comment out [this php 7.2 line in .travis.yml](https://github.com/saintsystems/odata-client-php/blob/master/.travis.yml#L10)?

**Pull request merged**
